name: Node.js CI

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js 14.17.0
      uses: actions/setup-node@v1
      with:
        node-version: '14.17.0'

    - name: Install dependencies
      run: npm ci

    - name: Test
      run: make test
